sudo: false
language: python
matrix:
    include:
        - python: "2.6"
          env: TOXENV=py26
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
          dist: xenial
install: pip install tox-travis python-coveralls
script: tox -e $TOXENV
after_success: coveralls
notifications:
    email: true
    irc:
        - "irc.freenode.net#jdcasey"
    on_success: change
    on_failure: always
